[build]
  base = "frontend"
  command = "npm install && npm run build"
  publish = "dist/frontend-app/browser"

  [build.environment]
    NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
